import { defineConfig } from "@internal/tsdown-config";

export default defineConfig({
  entry: "src/index.ts",
  dts: true,
  minify: false,
  clean: true,
  format: ["esm", "cjs"],
  external: [
    "@alifd/next",
    "@babel/parser",
    "@formily/antd",
    "@formily/core",
    "@formily/json-schema",
    "@formily/next",
    "@formily/react",
    "@formily/reactive",
    "@formily/reactive-react",
    "@formily/shared",
    "@monaco-editor/react",
    "@wordrhyme/designable-core",
    "@wordrhyme/designable-react",
    "@wordrhyme/designable-shared",
    "antd",
    "monaco-editor",
    "prettier",
    "react",
    "react-color",
    "react-dom",
    "react-is",
    "react-tiny-popover",
    "react/jsx-runtime",
  ],
});
